/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { MenteeFindManyArgs } from "../../mentee/base/MenteeFindManyArgs";
import { Mentee } from "../../mentee/base/Mentee";
import { MenteeWhereUniqueInput } from "../../mentee/base/MenteeWhereUniqueInput";
import { MentorFindManyArgs } from "../../mentor/base/MentorFindManyArgs";
import { Mentor } from "../../mentor/base/Mentor";
import { MentorWhereUniqueInput } from "../../mentor/base/MentorWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: data,
      select: {
        ageGroup: true,
        createdAt: true,
        email: true,
        firstName: true,
        gender: true,
        gpsLocation: true,
        id: true,
        language: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        ageGroup: true,
        createdAt: true,
        email: true,
        firstName: true,
        gender: true,
        gpsLocation: true,
        id: true,
        language: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        ageGroup: true,
        createdAt: true,
        email: true,
        firstName: true,
        gender: true,
        gpsLocation: true,
        id: true,
        language: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: data,
        select: {
          ageGroup: true,
          createdAt: true,
          email: true,
          firstName: true,
          gender: true,
          gpsLocation: true,
          id: true,
          language: true,
          lastName: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          ageGroup: true,
          createdAt: true,
          email: true,
          firstName: true,
          gender: true,
          gpsLocation: true,
          id: true,
          language: true,
          lastName: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/mentees")
  @ApiNestedQuery(MenteeFindManyArgs)
  async findMentees(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Mentee[]> {
    const query = plainToClass(MenteeFindManyArgs, request.query);
    const results = await this.service.findMentees(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/mentees")
  async connectMentees(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: MenteeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      mentees: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/mentees")
  async updateMentees(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: MenteeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      mentees: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/mentees")
  async disconnectMentees(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: MenteeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      mentees: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/mentors")
  @ApiNestedQuery(MentorFindManyArgs)
  async findMentors(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Mentor[]> {
    const query = plainToClass(MentorFindManyArgs, request.query);
    const results = await this.service.findMentors(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/mentors")
  async connectMentors(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: MentorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      mentors: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/mentors")
  async updateMentors(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: MentorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      mentors: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/mentors")
  async disconnectMentors(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: MentorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      mentors: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
