/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MentorService } from "../mentor.service";
import { MentorCreateInput } from "./MentorCreateInput";
import { Mentor } from "./Mentor";
import { MentorFindManyArgs } from "./MentorFindManyArgs";
import { MentorWhereUniqueInput } from "./MentorWhereUniqueInput";
import { MentorUpdateInput } from "./MentorUpdateInput";
import { PairingFindManyArgs } from "../../pairing/base/PairingFindManyArgs";
import { Pairing } from "../../pairing/base/Pairing";
import { PairingWhereUniqueInput } from "../../pairing/base/PairingWhereUniqueInput";

export class MentorControllerBase {
  constructor(protected readonly service: MentorService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Mentor })
  async createMentor(@common.Body() data: MentorCreateInput): Promise<Mentor> {
    return await this.service.createMentor({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Mentor] })
  @ApiNestedQuery(MentorFindManyArgs)
  async mentors(@common.Req() request: Request): Promise<Mentor[]> {
    const args = plainToClass(MentorFindManyArgs, request.query);
    return this.service.mentors({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Mentor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async mentor(
    @common.Param() params: MentorWhereUniqueInput
  ): Promise<Mentor | null> {
    const result = await this.service.mentor({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Mentor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMentor(
    @common.Param() params: MentorWhereUniqueInput,
    @common.Body() data: MentorUpdateInput
  ): Promise<Mentor | null> {
    try {
      return await this.service.updateMentor({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Mentor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMentor(
    @common.Param() params: MentorWhereUniqueInput
  ): Promise<Mentor | null> {
    try {
      return await this.service.deleteMentor({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/pairings")
  @ApiNestedQuery(PairingFindManyArgs)
  async findPairings(
    @common.Req() request: Request,
    @common.Param() params: MentorWhereUniqueInput
  ): Promise<Pairing[]> {
    const query = plainToClass(PairingFindManyArgs, request.query);
    const results = await this.service.findPairings(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        mentee: {
          select: {
            id: true,
          },
        },

        mentor: {
          select: {
            id: true,
          },
        },

        pairedAt: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/pairings")
  async connectPairings(
    @common.Param() params: MentorWhereUniqueInput,
    @common.Body() body: PairingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pairings: {
        connect: body,
      },
    };
    await this.service.updateMentor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/pairings")
  async updatePairings(
    @common.Param() params: MentorWhereUniqueInput,
    @common.Body() body: PairingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pairings: {
        set: body,
      },
    };
    await this.service.updateMentor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/pairings")
  async disconnectPairings(
    @common.Param() params: MentorWhereUniqueInput,
    @common.Body() body: PairingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pairings: {
        disconnect: body,
      },
    };
    await this.service.updateMentor({
      where: params,
      data,
      select: { id: true },
    });
  }
}
